import type { SubscriptionPlanId } from "@/services/subscriptions/types";

/**
 * A Subscription Access ID: proof that someone has paid for access to ONE host
 * under ONE plan.
 *
 * Deliberately a different class of credential from a Call ID. A Call ID says
 * "this is who you are calling" and is meant to be shared; an Access ID says
 * "this person may call them" and is not. They are never generated by the same
 * code, never resolved by the same function, and never stored together.
 *
 * The code itself is NOT stored. Only its hash is, so a copy of this database
 * does not hand anybody a working credential — which is the shape the Supabase
 * version has to have, and is worth getting right now rather than later.
 */
export type AccessIdStatus = "active" | "revoked";

export interface SubscriptionAccessId {
  id: string;
  profileId: string;
  planId: SubscriptionPlanId;
  /** SHA-256 of the normalised code. The code itself is never persisted. */
  codeHash: string;
  /** The last four characters, so a person can recognise their own credential. */
  codeLast4: string;
  status: AccessIdStatus;
  /** Set when the ID was issued off the back of a confirmed payment. */
  subscriptionRequestId: string | null;
  customerEmailNormalized: string | null;
  /** Who issued it. Development builds have no real admin identity yet. */
  issuedBy: string;
  createdAt: string;
  revokedAt: string | null;
  /**
   * Always null for now. The shape exists so an expiring credential does not
   * need a migration later; nothing in this phase expires.
   */
  expiresAt: string | null;
}

export interface GenerateAccessIdInput {
  profileId: string;
  planId: SubscriptionPlanId;
  subscriptionRequestId?: string | null;
  customerEmail?: string | null;
  issuedBy?: string;
}

/**
 * The one moment the plaintext code exists.
 *
 * Returned from generation and never again: there is nothing to read it back
 * from, by design. An admin who loses it issues another.
 */
export interface GeneratedAccessId {
  record: SubscriptionAccessId;
  /** Display form, e.g. CSUB-9K4P-48Q2. Never stored, never logged. */
  code: string;
}

/** What a valid credential resolves to, for the screen that welcomes someone back. */
export interface ResolvedAccess {
  record: SubscriptionAccessId;
  planId: SubscriptionPlanId;
  profileId: string;
}

export type AccessResolutionFailure =
  | "malformed"
  | "not_found"
  | "revoked"
  /** The credential is fine; the plan it was sold under is no longer offered. */
  | "plan_unavailable";

export type AccessResolution =
  | { ok: true; access: ResolvedAccess }
  | { ok: false; reason: AccessResolutionFailure };
