// Generated by scripts/fetch-transformation-models.mjs. Do not edit by hand.
// Models are Apache-2.0, published by Google; see public/transformation/models/manifest.json.
//
// The binaries these paths point at are gitignored and fetched by predev/prebuild.
// The generator verifies every file is on disk at a plausible size before writing
// this, so a path present here means the model was really there at build time.
export const transformationModelPaths = {
  faceLandmarker: "/transformation/models/face_landmarker.task",
  poseLandmarker: "/transformation/models/pose_landmarker_lite.task",
  imageSegmenter: null,
} as const;

/** When the generator last verified the binaries. Diagnostics only. */
export const transformationModelsPreparedAt = "2026-10-01T08:15:15.502Z";
